# .streamlit/secrets.toml

OPENAI_API_KEY = "sk-proj-*********************************************"

[connections.snowflake]
account = "jt****-hk****"
user = "ABHIJIT********"
password = "****************"
database = "<database>"
schema = "<schema>"
role = "<role>"
warehouse = "<warehouse>"